name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      shell: bash
      run: git submodule update --init --recursive

    - name: Setup Elm
      uses: justgook/setup-elm@v1

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        node-version: 12.x

    - name: Set yarn
      id: yarn
      run: |
        echo "::set-output name=dir::$(yarn cache dir)"
        echo "::add-path::$(yarn bin)"
        echo "::add-path::$(yarn global bin)"

    - name: Get Yarn cache
      uses: actions/cache@v1.0.3
      id: yarn-cache-exists
      with:
        path: ${{ steps.yarn.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/elm.json') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install elm-test
      run: yarn global add elm-test@0.19.1-revision2

    - name: Test
      env:
        ELM_HOME: ${{ steps.elm-home.outputs.dir }}
      run: elm-test
